import Layout from '@/views/layout/Layout'

const settingRouter = {
  path: '/setting',
  component: Layout,
  redirect: '/setting/auth',
  name: 'Api:setting',
  meta: {
    title: '设置模块',
    icon: 'set_up'
  },
  children: [{
      path: '/setting/auth',
      name: 'Api:setting/auth',
      component: () => import('@/views/setting/index'), // Parent router-view
      meta: { title: '用户模块', icon: 'user' },
      children: [],
      pid: 0
    },
    {
      path: 'user',
      name: 'Api:setting/auth/user-index',
      component: () => import('@/views/setting/user/users/index'),
      meta: { title: '角色列表', icon: 'product-list' },
      pid: 'Api:setting/auth',
    },
    {
      path: 'user/create',
      name: 'Api:setting/auth/user-store',
      component: () => import('@/views/setting/user/users/create'),
      meta: { title: ' 添加用户', icon: 'product-add' },
      pid: 'Api:setting/auth',
      hidden: true,
      isEdit: true,
    },
    {
      path: 'user/update',
      name: 'Api:setting/auth/user-update',
      component: () => import('@/views/setting/user/users/update'),
      meta: { title: '修改用户', icon: 'product-add' },
      pid: 'Api:setting/auth',
      hidden: true,
      isEdit: true,
    },
    {
      path: 'user/personal_update',
      name: 'Api:setting/auth/user-personal-update',
      component: () => import('@/views/setting/user/users/personalUpdate'),
      meta: { title: '个人中心修改用户', icon: 'product-add' },
      pid: 'Api:setting/auth',
      hidden: true,
      isEdit: true,
    },
    {
      path: 'role',
      name: 'Api:setting/auth/role-index',
      component: () => import('@/views/setting/user/role/index'),
      meta: { title: '组权限', icon: 'role' },
      pid: 'Api:setting/auth',
    },
    {
      path: 'permission',
      name: 'Api:setting/auth/permission-index',
      component: () => import('@/views/setting/user/permission/index'),
      meta: { title: '功能权限', icon: 'permission' },
      pid: 'Api:setting/auth',
    },
    {
      path: '/setting/system',
      name: 'Api:setting/system',
      component: () => import('@/views/setting/index'), // Parent router-view
      redirect: '/system/getConfig',
      meta: { title: '系统管理', icon: 'tools' },
      children: [],
      pid: 0
    },
    {
      path: 'getConfig',
      name: 'Api:setting/system/get_config-getConfig',
      component: () => import('@/views/setting/system/index/'),
      meta: { title: '系统配置', icon: 'product-list' },
      pid: 'Api:setting/system',
    },
    {
      path: 'getLog',
      name: 'Api:setting/system/get_operate_log-getList',
      component: () => import('@/views/setting/system/operateLog/'),
      meta: { title: '操作日志', icon: 'log' },
      pid: 'Api:setting/system',
    },
    {
      path: 'global_config',
      name: 'Api:setting/system/get_config-index',
      component: () => import('@/views/setting/system/global_config/index'),
      meta: { title: '全局配置', icon: 'setting_global' },
      pid: 'Api:setting/system',
    },
    {
      path: 'notice',
      name: 'Api:setting/system/notice-index',
      component: () => import('@/views/setting/system/notice/index'),
      meta: { title: '通知管理', icon: 'notice' },
      pid: 'Api:setting/system',
    },
    {
      path: 'notice/create',
      name: 'Api:setting/system/notice-store',
      component: () => import('@/views/setting/system/notice/create'),
      meta: { title: '添加通知', icon: 'notice' },
      pid: 'Api:setting/system',
      hidden: true,
      isEdit: true,
    },
    {
      path: 'notice/update',
      name: 'Api:setting/system/notice-update',
      component: () => import('@/views/setting/system/notice/update'),
      meta: { title: '修改通知', icon: 'notice' },
      pid: 'Api:setting/system',
      hidden: true,
      isEdit: true,
    },
    {
      path: 'advice',
      name: 'Api:setting/system/advice-index',
      component: () => import('@/views/setting/system/advice/index'),
      meta: { title: '建议管理', icon: 'notice' },
      pid: 'Api:setting/system',
      hidden: true,
    },
    {
      path: 'advice/create',
      name: 'Api:setting/system/advice-store',
      component: () => import('@/views/setting/system/advice/create'),
      meta: { title: '添加建议', icon: 'notice' },
      pid: 'Api:setting/system',
      hidden: true,
      isEdit: true,
    },
    {
      path: 'advice/update',
      name: 'Api:setting/system/advice-update',
      component: () => import('@/views/setting/system/advice/update'),
      meta: { title: '修改建议', icon: 'notice' },
      pid: 'Api:setting/system',
      hidden: true,
      isEdit: true,
    },
    {
      path: 'advice/reply',
      name: 'Api:setting/system/advice-reply',
      component: () => import('@/views/setting/system/advice/reply'),
      meta: { title: '回复建议', icon: 'notice' },
      pid: 'Api:setting/system',
      hidden: true,
      isEdit: true,
    },
    {
      path: 'control',
      name: 'Api:setting/system/control-getControlList',
      component: () => import('@/views/setting/system/control/index'),
      meta: { title: '后台控制', icon: 'switch' },
      pid: 'Api:setting/system',
    },

    {
      path: '/setting/technique',
      name: 'Api:setting/technique',
      component: () => import('@/views/setting/index'), // Parent router-view
      redirect: '/technique/sql_query',
      meta: { title: '技术开发', icon: 'technique' },
      children: [],
      pid: 0
    },
    {
      path: 'logs',
      name: 'Api:setting/system/system_log-getSystemLog',
      component: () => import('@/views/setting/technique/logs'),
      meta: { title: '日志系统', icon: 'logs' },
      pid: 'Api:setting/technique',
    },
    {
      path: 'log',
      name: 'Api:setting/system/log-getLogList',
      component: () => import('@/views/setting/technique/log'),
      meta: { title: '日志中心', icon: 'logs' },
      pid: 'Api:setting/technique',
    },
    {
      path: 'sql_query',
      name: 'Api:setting/technique/get_sql_result-getSqlResult',
      component: () => import('@/views/setting/technique/sqlQuery'),
      meta: { title: 'SQL查询', icon: 'setting_sql' },
      pid: 'Api:setting/technique',
    },
    {
      path: 'sql_export',
      name: 'Api:setting/technique/export_sql-exportSqlData',
      component: () => import('@/views/setting/technique/sqlExport'),
      meta: { title: '导出SQL', icon: 'sql_export' },
      pid: 'Api:setting/technique',
    },
    {
      path: 'test',
      name: 'Api:setting/technique/test-test',
      component: () => import('@/views/setting/technique/test'),
      meta: { title: '测试路由', icon: 'test' },
      pid: 'Api:setting/technique',
    },
    {
      path: 'json_decode',
      name: 'Api:setting/technique/json_decode-jsonDecode',
      component: () => import('@/views/setting/technique/jsonDecode'),
      meta: { title: 'JSON解析', icon: 'jsonDecode' },
      pid: 'Api:setting/technique',
    },
    {
      path: 'config_file',
      name: 'Api:setting/technique/config_file-getList',
      component: () => import('@/views/setting/technique/configFile'),
      meta: { title: '配置文件', icon: 'configFile' },
      pid: 'Api:setting/technique',
    },
    {
      path: 'file_center',
      name: 'Api:setting/technique/file_center-getList',
      component: () => import('@/views/setting/technique/fileCenter'),
      meta: { title: '文件中心', icon: 'fileCenter' },
      pid: 'Api:setting/technique',
    },
    {
      path: 'queue',
      name: 'Api:setting/technique/queue-getList',
      component: () => import('@/views/setting/technique/queue'),
      meta: { title: '队列异常', icon: 'queue' },
      pid: 'Api:setting/technique',
    },
    {
      path: 'horizon',
      name: 'Api:setting/technique/horizon-horizon',
      component: () => import('@/views/setting/technique/horizon'),
      meta: { title: 'Horizon控制台', icon: 'horizon' },
      pid: 'Api:setting/technique',
    },


  ]
};

export default settingRouter
